# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C05fBcyMwLVKVnUPgbZy0sCcD3POHfLx
"""

ip_str = input()
lst = [char for char in ip_str]
count = 0
val = 1
idx = -1
idx_last = -1

for i in range(len(lst)):
  if lst[i] == 'A':
    idx = i
    count = 1
  else:
    if lst[i] == 'Z' and count == 25:
      idx_last = i
      break
    if lst[i] == chr(65+val) and count>0:
      count+=1
      val += 1
print(idx_last-idx+1)

# ip_str = "FORCESABCDEFDIVGHIJKLMNOPQRSTUVWXYZ"
# lst = [char for char in ip_str]
# count = 0
# val = 1
# idx = -1
# idx_last = -1

# for i in range(len(lst)):
#   if lst[i] == 'A':
#     idx = i
#     count = 1
#   else:
#     if lst[i] == 'Z' and count == 25:
#       idx_last = i
#       break
#     if lst[i] == chr(65+val) and count>0:
#       count+=1
#       val += 1
# print(idx_last-idx+1)

# ip_str = "ABCDEFDIVGHIJKLMNICPCOPQRSTUVWXYZ"
# lst = [char for char in ip_str]
# count = 0
# val = 1
# idx = -1
# idx_last = -1

# for i in range(len(lst)):
#   if lst[i] == 'A':
#     idx = i
#     count = 1
#   else:
#     if lst[i] == 'Z' and count == 25:
#       idx_last = i
#       break
#     if lst[i] == chr(65+val) and count>0:
#       count+=1
#       val += 1
# print(idx_last-idx+1)

